"""Phase 4: Blind Audit — Claude reviews code without seeing the coder's explanation first."""

import json
import re

from ..models import SessionState, AuditResult, AuditIssue
from ..providers.base import LLMProvider


def run_audit(
    state: SessionState,
    claude: LLMProvider,
    on_message=None,
) -> AuditResult:
    """Claude reviews the generated code in a 'blind' audit.

    Blind = Claude sees the code and the plan, but NOT the coder's
    explanation of what they did. This prevents anchoring bias.

    Args:
        state: Session state with code result
        claude: Claude CLI provider
        on_message: Optional callback for live output
    """
    code_result = state.code_result

    # Format code for review
    code_display = ""
    for f in code_result.files:
        code_display += f"\n--- {f.path} ({f.action}) ---\n{f.content}\n"

    prompt = f"""BLIND CODE REVIEW

You are reviewing code generated by your partner (Senior Developer) for the task below.
You have NOT seen their explanation of what they did — form your own opinion first.

ORIGINAL TASK: {state.task}

AGREED PLAN:
{state.plan.agreed_plan[-2000:]}

GENERATED CODE:
{code_display}

Review for:
1. CORRECTNESS: Does the code actually implement what was planned? Any logic bugs?
2. SECURITY: Any vulnerabilities? (injection, auth bypass, insecure defaults, etc.)
3. COMPLETENESS: Are all planned features implemented? Any missing pieces?
4. CODE QUALITY: Is it clean, maintainable, and following good practices?
5. PLAN ADHERENCE: Does it match the agreed architecture and decisions?

Be thorough but fair. If the code is solid, say so.
If there are issues, be specific about what's wrong and how to fix it.

End your review with a verdict:
APPROVED — if the code is ready to ship
REJECTED — if changes are needed (list specific issues)
"""

    system_prompt = f"""You are a Technical Architect conducting a blind code review.
You must form your own independent assessment before accepting any code.
Be rigorous but fair — don't nitpick style issues, focus on correctness and security.
Expert domains: {', '.join(state.analysis.required_expertise)}"""

    response = claude.send(prompt, system_prompt=system_prompt)

    if not response.success:
        if on_message:
            on_message("claude", "Architect", f"[ERROR] {response.error}")
        return AuditResult(
            approved=False,
            assessment=f"Audit failed: {response.error}",
            feedback_for_coder="Audit could not be completed due to an error.",
        )

    if on_message:
        on_message("claude", "Architect (Audit)", response.content)

    # Determine if approved or rejected
    approved = _detect_approval(response.content)

    # Extract specific issues
    issues = _extract_issues(response.content)

    # Build feedback for coder (if rejected)
    feedback = ""
    if not approved:
        feedback = response.content  # full review as feedback

    return AuditResult(
        approved=approved,
        assessment=response.content,
        issues=issues,
        feedback_for_coder=feedback,
    )


def _detect_approval(text: str) -> bool:
    """Determine if the audit approved or rejected the code."""
    lower = text.lower()

    # Look for explicit verdict markers
    if "approved" in lower and "rejected" not in lower:
        return True
    if "rejected" in lower:
        return False

    # Look for verdict section
    lines = text.split("\n")
    for line in reversed(lines):
        line_lower = line.strip().lower()
        if line_lower.startswith("verdict"):
            return "approved" in line_lower and "rejected" not in line_lower
        if line_lower.startswith("approved"):
            return True
        if line_lower.startswith("rejected"):
            return False

    # Default to not approved if unclear
    return False


def _extract_issues(text: str) -> list[AuditIssue]:
    """Extract specific issues from the audit review."""
    issues = []

    # Look for numbered or bulleted issues
    issue_patterns = [
        r'(?:issue|problem|bug|vulnerability|concern)\s*(?:\d+)?[:.]\s*(.+)',
        r'[-*]\s*(?:CRITICAL|HIGH|MEDIUM|LOW)[:.]\s*(.+)',
    ]

    for pattern in issue_patterns:
        matches = re.findall(pattern, text, re.IGNORECASE)
        for match in matches:
            # Try to determine severity
            severity = "medium"
            match_lower = match.lower()
            if any(kw in match_lower for kw in ["critical", "security", "vulnerability", "injection"]):
                severity = "critical"
            elif any(kw in match_lower for kw in ["high", "bug", "incorrect", "wrong"]):
                severity = "high"
            elif any(kw in match_lower for kw in ["low", "style", "naming", "minor"]):
                severity = "low"

            issues.append(AuditIssue(
                severity=severity,
                file="",  # would need smarter parsing to extract
                issue=match.strip(),
                suggested_fix="",
            ))

    return issues
